# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('current_price', models.IntegerField()),
                ('close_price', models.IntegerField()),
                ('open_price', models.IntegerField()),
                ('high_price', models.IntegerField()),
                ('low_price', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
