# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_customers_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='close_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='high_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open_price',
            field=models.FloatField(),
        ),
    ]
